[discovery]
ignore = ["vendor", "luau_packages", ".git"]
gitignore = true

[discovery.lute]
require = "@lutest_release"
roots = ["core", "lib", "runtimes", "cli", "utils"]

[discovery.roblox]
require = "ReplicatedStorage.Packages.lutest"
roots = ["game"]

[roblox]
universe_id = 10460283574
place_id = 87484847405188
